name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Write key
        if: github.event_name != 'pull_request' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' )
        run: |
          echo storePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
          echo keyAlias='${{ secrets.ALIAS }}' >> local.properties
          echo keyPassword='${{ secrets.ALIAS_KEY_PASSWORD }}' >> local.properties
          echo fileDir='../key.jks' >> local.properties
          echo '${{ secrets.SIGNING_KEY_BASE64 }}' | base64 --decode > key.jks

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-manager-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            gradle-deps

      - name: Cache Gradle Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-manager-${{ github.sha }}
          restore-keys: |
            gradle-builds

      - name: Build with Gradle
        id: buildRelease
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew assemble
          sudo apt install -y apksigner
          echo '${{ secrets.SIGNING_KEY_BASE64 }}' | base64 --decode > key.jks
          apksigner sign --ks key.jks --ks-pass 'pass:${{ secrets.KEY_STORE_PASSWORD }}' "`ls app/build/outputs/apk/release/DashBoard*-v*-release.apk`"
          echo "::set-output name=releaseName::`ls app/build/outputs/apk/release/DashBoard*-v*-release.apk | awk -F '(/|.apk)' '{print $6}'`"
          echo "::set-output name=debugName::`ls app/build/outputs/apk/debug/DashBoard*-v*-debug.apk | awk -F '(/|.apk)' '{print $6}'`"

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: "app/build/outputs/apk/release/*.apk"
          generate_release_notes: true